### ISSUE TITLE
association_ids(collection_singular_ids) support

### ISSUE THREAD

**Issue by zeitnot** [DmitryTsepelev/ar_lazy_preload#27]
Let's say `User` has many `posts`. `User.lazy_preload(:posts).map(&:posts)` works perfect. But if I want ids with `User.lazy_preload(:posts).map(&:post_ids)` it does N+1 queries.

I have tried to add support for `association_ids` but I could not manage to implement it. Could you give some hints so that I can implement it and send a pull request?

**Comment by DmitryTsepelev** [comment]
Hi @zeitnot! I've taken a quick look, here is what I've found:

1. as you mentioned, we're interested in `collection_singular_ids`, which is generated [here](https://github.com/rails/rails/blob/b30a23f53b52e59d31358f7b80385ee5c2ba3afe/activerecord/lib/active_record/associations/builder/collection_association.rb#L54);
2. it calls `ids_reader` method on `association` object, and here is the [implementation](https://github.com/rails/rails/blob/3dff30c14fa25f211088d62da26611616ab5616f/activerecord/lib/active_record/associations/collection_association.rb#L45);
3. ( I haven't checked this assumption, it's just a guess:) since the association is not loaded, it goes to `else` [branch](https://github.com/rails/rails/blob/3dff30c14fa25f211088d62da26611616ab5616f/activerecord/lib/active_record/associations/collection_association.rb#L51), causing Rails to call `pluck` (and make the request) for each object in the collection.

I'd suggest to do the following:

1. Make sure I'm not wrong about calling `pluck` on scopes (and this is the source of N+1)
2. Consider patching [CollectionAssociation](https://github.com/rails/rails/blob/3dff30c14fa25f211088d62da26611616ab5616f/activerecord/lib/active_record/associations/collection_association.rb#L28) to avoid N+1 (we already patch Association [here](https://github.com/DmitryTsepelev/ar_lazy_preload/blob/master/lib/ar_lazy_preload/active_record/association.rb))

**Comment by zeitnot** [comment]
Thanks @DmitryTsepelev for fast response. I have created the pr.
